const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const srcDir = path.join(root, 'src/js');
const outFile = path.join(root, 'assets/js/main.js');

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function transformSupabaseStub(content) {
  return content.replace(/export\s+function\s+createClient/, 'function __supabaseCreateClient');
}

function transformSupabaseClient(content) {
  return content
    .replace(/import\s+{\s*createClient\s*}\s+from\s+'@supabase\/supabase-js';\n/, '')
    .replace(/export\s+function\s+createSupabaseClient\s*\(/, 'function createSupabaseClient(')
    .replace(/createClient\(/g, '__supabaseCreateClient(');
}

function transformConfig(content) {
  return content.replace(/export\s+const\s+/g, 'const ');
}

function transformMain(content) {
  return content
    .replace(/import\s+{\s*createSupabaseClient\s*}\s+from\s+'\.\/supabaseClient\.js';\n/, '')
    .replace(/import\s+{[\s\S]*?}\s+from\s+'\.\/config\.js';\n/, '');
}

function build() {
  const supabaseStub = transformSupabaseStub(
    read(path.join(srcDir, 'vendor/supabaseStub.js')),
  );
  const supabaseClient = transformSupabaseClient(
    read(path.join(srcDir, 'supabaseClient.js')),
  );
  const config = transformConfig(read(path.join(srcDir, 'config.js')));
  const main = transformMain(read(path.join(srcDir, 'main.js')));

  const banner = '// Auto-generated by scripts/build.js';
  const contents = `(() => {\n${supabaseStub}\n\n${config}\n\n${supabaseClient}\n\n${main}\n})();\n`;

  fs.writeFileSync(outFile, `${banner}\n${contents}`);
}

build();
